# GO 富集及可视化

## GO 分类

```{r}
library(clusterProfiler)
library(org.My.eg.db, lib.loc = "13.function/R_Library/")
ggo <- groupGO(gene     = gene,
               OrgDb    = org.My.eg.db,
               keyType  = "GID",
               ont      = "BP",
               level    = 3,
               readable = FALSE)
head(ggo)
```

## GO over-representation 富集

```{r}
ego <- enrichGO(gene          = gene,
                universe      = names(geneList),
                OrgDb         = org.My.eg.db,
                keyType       = "GID",
                ont           = "BP",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.05,
                readable      = FALSE)
ego_df <- as.data.frame(ego)
```

### 富集结果优化

1. 去除部分 term

```{r}
# 去除 level 1,2,3
ego <- dropGO(ego, level = 1:3) %>%
  # 去除包含 drug 的GO
  filter(!str_detect(Description, "drug"))
```

2. 去除冗余 term

```{r}
ego <- enrichplot::pairwise_termsim(ego)
ego <- clusterProfiler::simplify(ego, cutoff=0.7, 
                                 by="p.adjust", 
                                 select_fun=min)
```

### 可视化

```{r}
goplot(ego)
```

```{r}
barplot(ego, showCategory = 15)
```

```{r}
dotplot(ego, showCategory = 15)
```

```{r}
cnetplot(ego, foldChange=geneList)
```